version: "3.7"

services:
  postgresql-companies:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=companies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-companies-data:/var/lib/postgresql/data
volumes:
  postgresql-companies-data:
